;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC grpc.fin.IngressService Client Implementation
;;;----------------------------------------------------------------------------------
(ns grpc.fin.IngressService.client
  (:require [grpc.fin :refer :all]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn getTransactions
  ([client params] (getTransactions client {} params))
  ([client metadata params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "grpc.fin.IngressService"
              :method  "getTransactions"
              :input   {:f grpc.fin/new-GetTransactionsRequest :ch input}
              :output  {:f grpc.fin/pb->GetTransactionsResponse :ch output}
              :metadata metadata}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output)))))))

